// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import * as ph from "@plasmicapp/host";

import { ScreenVariantProvider } from "../components/plasmic/blank_project/PlasmicGlobalVariant__Screen";
import { PlasmicHomepage } from "../components/plasmic/blank_project/PlasmicHomepage";
import { useRouter } from "next/router";
import Select__Option from "../components/Select__Option";


function Homepage() {
 
  return (
    <ph.PageParamsProvider
      params={useRouter()?.query}
      query={useRouter()?.query}
    >
      <PlasmicHomepage
        theme={{
          props: {
            children:[
              <Select__Option value="1" children="1" />,
              <Select__Option value="2" children="2" />,
              <Select__Option value="12" children="12" />,
              <Select__Option value="13" children="13" />,
            ]
          },
        }}
      />
    </ph.PageParamsProvider>
  );
}

export default Homepage;
